---
# replace_kernel-default-base_with_kernel-default/tasks/main.yml

- name: 'Force installation of kernel-default instead of kernel-default-base'
  community.general.zypper:
    name:
      - '-kernel-default-base'
      - 'kernel-default'
    state: 'installed'
  when: 'ansible_os_family == "Suse"'
  notify:
    - "Reboot"
    - "Wait for the machine(s) to be ready again"
